# Generated by Django 3.2.20 on 2023-09-04 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('EXPENCES', 'EXPENCES'), ('DONATIONS', 'DONATIONS')], max_length=10)),
                ('payment_status', models.CharField(choices=[('FULL', 'FULL'), ('ADVANCED', 'ADVANCED'), ('PARTIAL', 'PARTIAL')], max_length=10)),
                ('bill_name', models.CharField(max_length=100)),
                ('bill_description', models.TextField(max_length=500)),
                ('bill_paid_to', models.TextField(max_length=100)),
                ('bill_received_by', models.TextField(max_length=100)),
                ('bill_amount', models.IntegerField()),
                ('paid_amount', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transacion_type', models.CharField(choices=[('FULL', 'FULL'), ('ADVANCED', 'ADVANCED'), ('PARTIAL', 'PARTIAL')], max_length=100)),
                ('transaction_amount', models.IntegerField()),
                ('payemnt_method', models.CharField(choices=[('CASH', 'CASH'), ('ONLINE', 'ONLINE')], max_length=100)),
                ('receipt', models.CharField(max_length=357)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.payments')),
            ],
        ),
    ]
