# Generated by Django 3.2.20 on 2023-09-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_status',
            field=models.CharField(choices=[('FULL', 'FULL'), ('ADVANCED', 'ADVANCED'), ('PARTIAL', 'PARTIAL'), ('INITIADED', 'INITIAD')], default='INITIADED', max_length=10),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_type',
            field=models.CharField(choices=[('EXPENCES', 'EXPENCES'), ('DONATIONS', 'DONATIONS')], default='EXPENCES', max_length=10),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='payemnt_method',
            field=models.CharField(choices=[('CASH', 'CASH'), ('ONLINE', 'ONLINE')], default='CASH', max_length=100),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transacion_type',
            field=models.CharField(choices=[('FULL', 'FULL'), ('ADVANCED', 'ADVANCED'), ('PARTIAL', 'PARTIAL'), ('INITIADED', 'INITIAD')], default='ADVANCED', max_length=100),
        ),
    ]
