# Generated by Django 3.2.20 on 2023-09-15 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20230905_0013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='bill_paid_to',
            new_name='bill_paid_by',
        ),
    ]
