# Generated by Django 3.2.20 on 2023-09-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_transactions_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='receipt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
