# Generated by Django 3.2.20 on 2023-09-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activites',
            name='status',
            field=models.CharField(choices=[('ON_GOING', 'ON_GOING'), ('UP_COMING', 'UP_COMING'), ('COMPLETED', 'COMPLETED')], default='UP_COMING', max_length=10),
        ),
        migrations.AlterField(
            model_name='eventmembers',
            name='added_through',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('MANAGER', 'MANAGER'), ('INVITED', 'INVITED')], default='MANAGER', max_length=10),
        ),
        migrations.AlterField(
            model_name='eventmembers',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('MANAGER', 'MANAGER'), ('VOLUNTEER', 'VOLUNTEER')], default='VOLUNTEER', max_length=10),
        ),
    ]
