# Generated by Django 3.2.20 on 2023-09-08 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20230908_2239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventmembers',
            old_name='CustomUser_id',
            new_name='user_id',
        ),
    ]
