# Generated by Django 3.2.20 on 2023-09-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_eventmembers_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_pic',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.CharField(max_length=5000),
        ),
    ]
